site_name: ASF Data Search Manual
site_url: https://search.asf.alaska.edu/
site_description: Documentation for searching and processing ASF data.
site_dir: 'docs'
docs_dir: 'markdown-docs'
copyright: Copyright @ Alaska Satellite Facility
google_analytics: ['UA-991100-5', 'search.asf.alaska.edu']

theme:
  name: "material"
  logo: images/ASFLogo-Blue2.png
  favicon: images/favicon.ico
  features:
    - navigation.instant

extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/AKSatellite/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Ak_Satellite
    - icon: fontawesome/brands/youtube-square
      link: https://www.youtube.com/channel/UChCfI0oVWw4qDwEidnDskJQ

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - Search UI:
    - Vertex Manual: vertex/manual.md
    - Tutorial Videos: https://www.youtube.com/playlist?list=PLXluIEvp5ZzIWd0yNy-ANfdwWjCD1hInA
    - Source Code: https://github.com/asfadmin/Discovery-SearchUI
  - On Demand Processing:
    - Overview: on_demand.md
    - ASF Hyp3: '!include ./hyp3-docs/mkdocs.yml'
  - About: about.md
  - ASF Web: 'https://asf.alaska.edu/'

plugins:
  - monorepo
  - gitsnippet
  - mkdocstrings:
      handlers:
          python:
            inherited_members: True
